assignment(hold1, false).
assignment(hold2, true).
assignment(m1f, false).
assignment(m1t, false).
assignment(m2f, true).
assignment(m2t, false).
assignment(p1, false).
assignment(p2, false).
assignment(p3, true).
assignment(p4, false).
assignment(q1, false).
assignment(q2, true).
assignment(q3, false).
assignment(q4, false).
assignment(o_u1, false).
assignment(o_u2, true).
assignment(o_u3, true).
assignment(o_u4, true).
assignment(o_u5, true).
assignment(o_u6, false).
assignment(o_v1, true).
assignment(o_v2, true).
assignment(o_v3, true).
assignment(o_v4, false).
assignment(o_v5, false).
assignment(o_v6, true).
