assignment('q1', 0).
assignment('q2', 0).
assignment('q3', 0).
assignment('q4', 1).
assignment('p1', 0).
assignment('p2', 0).
assignment('p3', 0).
assignment('p4', 1).
assignment('m2f', 0).
assignment('m2t', 1).
assignment('m1f', 0).
assignment('m1t', 1).
assignment('hold1', 0).
assignment('hold2', 1).
assignment('u1', 1).
assignment('u2', 1).
assignment('u3', 0).
assignment('u4', 0).
assignment('u5', 1).
assignment('u6', 0).
assignment('v1', 2).
assignment('v2', 0).
assignment('v3', 2).
assignment('v4', 0).
assignment('v5', 2).
assignment('v6', 1).
