assignment(m1f, true).
assignment(hold1, true).
assignment(q1, false).
assignment(q2, false).
assignment(p1, false).
assignment(q3, true).
assignment(m2f, false).
assignment(p2, true).
assignment(hold2, false).
assignment(m2t, false).
assignment(m1t, false).
assignment(q4, false).
assignment(p4, false).
assignment(p3, false).