assignment(t1, 1).
assignment(t2, 0).
assignment(t3, 1).
assignment(s1, false).
assignment(s2, false).
assignment(s3, true).
assignment(s4, false).
assignment(s5, false).
assignment(s6, true).
assignment(o_t1, true).
assignment(o_t3, true).
