assignment(t1, 1).
assignment(t2, 0).
assignment(t3, 1).
assignment(s1, false).
assignment(s2, false).
assignment(s3, true).
assignment(s4, false).
assignment(s5, false).
assignment(s6, false).
assignment(b_t1, false).
assignment(b_t2, true).
assignment(b_t3, true).
