#!/bin/bash

# **********************************************************************
# Preamble

function absolute_path {
    (cd "$(dirname "$1")" && pwd)
}

function print_title {
    cat <<EOF
PETRINIZER: The checker for Petri Nets
[$1]
EOF
}

function print_usage {
    cat <<EOF

Usage: $0 [options] input_file
Option list:
 -h | --h | -help | --help    : Prints this help

EOF
}


# **********************************************************************
# Entry point

print_title "$*"

# parse parameters
for a in $@; do
    case $a in
        -h | --h | -help | --help)
            print_usage
            exit 0
            ;;
        -*)
            echo 'ERROR: Unknown option '$a
            exit 2
            ;;
        *) input=$a ;;
    esac
done

if [ -z "$input" ]; then
    echo 'ERROR: No input file was given'
    exit 1
fi

sysdir=$(absolute_path $0)

set -e
set -o pipefail

echo
echo '- Constructing petri net N from input file'
echo
sicstus -l $sysdir/input-file-to-petri-net.pl -- `pwd`/$input 2>/dev/null | tee /tmp/pp-petri-net.pl

echo
echo '- Constructing constraints C0 for petri net N'
echo
sicstus -l $sysdir/petri-net-to-constraints.pl -- /tmp/pp-petri-net.pl 2>/dev/null | tee /tmp/constraints-c.smt2

echo
echo '- Checking SAT(C0)'
echo
if ! z3 -smt2 /tmp/constraints-c.smt2 | tee /tmp/model-a.smt2; then exit; fi
# while ! z3 -smt2 /tmp/constraints-c.smt2 | tee /tmp/model-a.smt2; do

    echo
    echo '- Constructing trap conditions C_theta for model A'
    echo
    cat /tmp/model-a.smt2 | $sysdir/smt2-model-to-prolog-model.sh | tee /tmp/model-a.pl
    sicstus -l $sysdir/trap-conditions.pl -- /tmp/petri-net.pl /tmp/model-a.pl 2>/dev/null | tee /tmp/constraints-ctheta.smt2

    echo
    echo '- Checking SAT(C_theta)'
    echo
    if ! z3 -smt2 /tmp/constraints-ctheta.smt2 | tee /tmp/model-atheta.smt2; then
        echo '-------------------------------------------'
        echo 'The petri net may not satisfy the property'
        echo '-------------------------------------------'
        exit 1
    fi

    echo
    echo '- Constructing trap conditions C_n+1 for model A_theta'
    echo
    cat /tmp/model-atheta.smt2 | $sysdir/smt2-model-to-prolog-model.sh | tee /tmp/model-atheta.pl
    sicstus -l $sysdir/delta-condition.pl -- /tmp/model-atheta.pl 2>/dev/null | tee /tmp/delta-condition.smt2
    
# done

set +o pipefail
set +e